name: Test my sum-server
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.11.0
      - name: Run npm install
        run: npm install
      - name: Run tests
        run: npm run test
